# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_cached_document}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Gibbons"]
  s.date = %q{2010-04-09}
  s.description = %q{Adds support for caching Mongoid documents as a field within other Mongoid documents, with complete control over which fields to cache.}
  s.email = %q{mhgibbons@me.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongoid/cached_document.rb",
     "mongoid_cached_document.gemspec",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/mongoid/cached_document_spec.rb"
  ]
  s.homepage = %q{http://github.com/accuser/mongoid_cached_document}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Document caching for Mongoid}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/unit/mongoid/cached_document_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta2"])
  end
end

